version: '2'
services:
  consul:
    image: consul:latest
    command: agent -server -dev -log-level debug
    network_mode: host

  nsqlookupd-1:
    image: nsqio/nsq
    command: >
      /nsqlookupd
      -broadcast-address localhost:4160
    ports:
      - 4160:4160
      - 4161:4161

  nsqlookupd-2:
    image: nsqio/nsq
    command: >
      /nsqlookupd
      -broadcast-address localhost:4162
    ports:
      - 4162:4160
      - 4163:4161

  nsqlookupd-3:
    image: nsqio/nsq
    command: >
      /nsqlookupd
      -broadcast-address localhost:4164
    ports:
      - 4164:4160
      - 4165:4161

  nsqd-1:
    image: nsqio/nsq
    command: >
      /nsqd
      -broadcast-address localhost:4150
      -lookupd-tcp-address nsqlookupd-1:4160
      -lookupd-tcp-address nsqlookupd-2:4160
      -lookupd-tcp-address nsqlookupd-3:4160
    ports:
      - 4150:4150
      - 4151:4151
    depends_on:
      - nsqlookupd-1
      - nsqlookupd-2
      - nsqlookupd-3

  nsqd-2:
    image: nsqio/nsq
    command: >
      /nsqd
      -broadcast-address localhost:4152
      -lookupd-tcp-address nsqlookupd-1:4160
      -lookupd-tcp-address nsqlookupd-2:4160
      -lookupd-tcp-address nsqlookupd-3:4160
    ports:
      - 4152:4150
      - 4153:4151
    depends_on:
      - nsqlookupd-1
      - nsqlookupd-2
      - nsqlookupd-3

  nsqd-3:
    image: nsqio/nsq
    command: >
      /nsqd
      -broadcast-address localhost:4154
      -lookupd-tcp-address nsqlookupd-1:4160
      -lookupd-tcp-address nsqlookupd-2:4160
      -lookupd-tcp-address nsqlookupd-3:4160
    ports:
      - 4154:4150
      - 4155:4151
    depends_on:
      - nsqlookupd-1
      - nsqlookupd-2
      - nsqlookupd-3

  nsqadmin:
    image: nsqio/nsq
    command: >
      /nsqadmin
      -lookupd-http-address nsqlookupd-1:4161
      -lookupd-http-address nsqlookupd-2:4161
      -lookupd-http-address nsqlookupd-3:4161
    ports:
      - 4171:4171
    depends_on:
      - nsqlookupd-1
      - nsqlookupd-2
      - nsqlookupd-3
